### ISSUE TITLE
Support for answers in the form of "When is..."

### ISSUE THREAD

**Issue by jaredsilver** [gesteves/trebekbot#10]
trebekbot: "The category is `answers that start with "feb"` for $200: `Buy me a drink & I'll be your sweetie on Valentine's Day, this date" 

Me: "trebekbot when is February 14?"

trebekbot: "That is correct, Jared, but responses have to be in the form of a question. Your total score is $146,300."

**Comment by gesteves** [comment]
Good catch, I'll add it soon.

**Comment by jeffharrington** [comment]
Pull Request https://github.com/gesteves/trebekbot/pull/12 submitted
