### ISSUE TITLE
Question Error

### ISSUE THREAD

**Issue by kharasoft** [gesteves/trebekbot#14]
The category is `it's greek myth to me` for $1,000: `This god is a brother of Zeus`

I answered Hades and was told it's wrong answer. The bot was looking for Poseidon but Hades is also Zeus' brother.

**Comment by sottenad** [comment]
Hey @kharasoft, this is @sottenad the author of the service that trebekbot consumes. All the questions and answers come from jarchive.com, an online transcript of every jeopardy question. 

I am looking into ways to keep the data clean, and have put a counter on each question for the number of times it has been marked as "invalid" as a rudimentary way to flag questions. @gesteves - maybe you could program trebekbot to listen for another keyword after the question to forward a request to /api/invalid with the question id? Then start skipping questions that have more than a certain amount of votes? Just a thought. Overall though Jeopardy! vets their questions pretty well from what I can tell.

**Comment by kharasoft** [comment]
I had some ideas for getting involved. Like having a "judges review" where the channel can determine if an answer is close enough.

Also thinking about having running scoreboards like daily weekly etc

Sent from my iPhone

On Apr 24, 2015, at 6:28 PM, Steve Ottenad <notifications@github.com<mailto:notifications@github.com>> wrote:


Hey @kharasoft<https://github.com/kharasoft>, this is @sottenad<https://github.com/sottenad> the author of the service that trebekbot consumes. All the questions and answers come from jarchive.com<http://jarchive.com>, an online transcript of every jeopardy question.

I am looking into ways to keep the data clean, and have put a counter on each question for the number of times it has been marked as "invalid" as a rudimentary way to flag questions. @gesteves<https://github.com/gesteves> - maybe you could program trebekbot to listen for another keyword after the question to forward a request to /api/invalid with the question id? Then start skipping questions that have more than a certain amount of votes? Just a thought. Overall though Jeopardy! vets their questions pretty well from what I can tell.

-

**Comment by gesteves** [comment]
@sottenad That sounds reasonable, I'll see what I can do.
