### ISSUE TITLE
Reset scores 

### ISSUE THREAD

**Issue by tr1age** [gesteves/trebekbot#20]
how do we reset the scores?

**Comment by jeffcampbell** [comment]
I run a little cron job that creates a new database on a weekly schedule. It's a simple solution to reset the scores.

```
heroku addons:destroy rediscloud --app $yourappname --confirm $yourappname

heroku addons:create rediscloud --app $yourappname --confirm $yourappname

heroku restart --app meetup-jeopardy
```

**Comment by dustinthewolf** [comment]
If you flush memory on the rediscloud it reset the scores.
