### ISSUE TITLE
Explanations in parentheses cause correct answers to be marked wrong

### ISSUE THREAD

**Issue by mattsheets** [gesteves/trebekbot#22]
Some answers have explanations in parentheses, that Trebek would presumably read out loud on the show. In this version, though, it causes correct answers to be judged wrong because our answers are different enough from the given answer. It would be nice if we could ignore explanations in the parentheses when deciding whether an answer is correct.

**Example:**
<img width="876" alt="screenshot 2015-08-17 13 42 12" src="https://cloud.githubusercontent.com/assets/2053190/9313007/08e9bba4-44e6-11e5-8736-43ae3293d464.png">

**Comment by lunchbag** [comment]
+1, saw this with "a vet (doc accepted)" as the answer
