### ISSUE TITLE
Sean Connery

### ISSUE THREAD

**Issue by karlashi** [gesteves/trebekbot#7]
Hi, thanks for the simple steps to deploy, I'm new to this things. Why does the bot not recognize the different people and takes us all as Sean Connery? I don't know if there's any info regarding my setup that would help you, I deployed using heroku.
Thanks!!!

**Comment by gesteves** [comment]
Make sure you have an API token for Slack set up properly in trebekbot.

1. Go to https://api.slack.com/web, log in, and copy the token at the bottom of the page.
![screen shot 2015-01-30 at 11 07 25 am](https://cloud.githubusercontent.com/assets/6379/5978779/498da12e-a870-11e4-8bcb-6d4bc50bd09f.png)  

2. Go to your [Heroku dashboard](https://dashboard.heroku.com), find your trebekbot app, go to "settings", press the "reveal config vars" button, click "edit", and make sure there's a config var with key `API_TOKEN` and value the token you copied before.
![screen shot 2015-01-30 at 11 09 52 am](https://cloud.githubusercontent.com/assets/6379/5978814/a81cf74e-a870-11e4-9ef9-07adb9b17de5.png)

3. In the same Heroku dashboard, go to "resources" and click on Redis Cloud. Click on your redis database there, and then press the "flush memory" button to reset your db.
![screen shot 2015-01-30 at 11 13 01 am](https://cloud.githubusercontent.com/assets/6379/5978861/092ad4e8-a871-11e4-8da5-65d99538df88.png)

**Comment by karlashi** [comment]
it worked! Thanks!! With that I also reset the scores, right?

**Comment by gesteves** [comment]
Yep. Hopefully you won't need to do this again.

**Comment by jdan** [comment]
@gesteves Have they changed around their docs? Can't seem to find a token on that link.

**Comment by gesteves** [comment]
@jdan Yeah looks like they changed their page, and now they call them test tokens: https://api.slack.com/docs/oauth-test-tokens

**Comment by jdan** [comment]
@gesteves Great, thanks for the quick response! We're loving the bot in our Slack, just making sure using a test token wasn't too absurd.

**Comment by gesteves** [comment]
Great to hear! But yeah, at some point I want to make this into a real Slack app with an "add to slack" button so it's easier to install, it's too convoluted right now.
